services:
  db:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: todo-db
    ports:
      - "${NEXT_PUBLIC_JSON_SERVER_PORT}:${NEXT_PUBLIC_JSON_SERVER_PORT}"
    volumes:
      - db:/data/db
    command: >
      sh -c "pnpm dlx json-server --watch server/db.json --port ${NEXT_PUBLIC_JSON_SERVER_PORT}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-app
    ports:
      - "${NEXT_PUBLIC_APP_PORT}:${NEXT_PUBLIC_APP_PORT}"
    depends_on:
      - db

volumes:
  db:
