services:
  db:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - .env.production
    ports:
      - "${NEXT_PUBLIC_JSON_SERVER_PORT}:${NEXT_PUBLIC_JSON_SERVER_PORT}"
    volumes:
      - db:/data/db
    command: >
      sh -c "pnpm dlx json-server --watch db.json --port ${NEXT_PUBLIC_JSON_SERVER_PORT}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "${NEXT_PUBLIC_APP_PORT}:${NEXT_PUBLIC_APP_PORT}"
    depends_on:
      - db

volumes:
  db:
