services:
  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

  json-server:
    build: 
      context: ./server
      dockerfile: Dockerfile    
    volumes:
      - json-data:/server/db.json
    ports:
      - ${JSON_SERVER_PORT}:${JSON_SERVER_PORT}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - db
      - json-server

volumes:
  db:
  json-data:

