version: '3.8' 
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: todos
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://json-server:3001" 
    depends_on:
      - db

volumes:
  db:
