services:
  db:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: todo-db
    ports:
      - "${NEXT_PUBLIC_JSON_SERVER_PORT}:${NEXT_PUBLIC_JSON_SERVER_PORT}"
    volumes:
      - db:/data/db
    command: >
      sh -c "pnpm dlx json-server --watch server/db.json --port ${NEXT_PUBLIC_JSON_SERVER_PORT}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./src
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - "${NEXT_PUBLIC_NGINX_PORT}:${NEXT_PUBLIC_NGINX_PORT}"
    depends_on:
      - app

volumes:
  db:
