export const lang = {
  metadata: {
    title: "Todo list",
    description: "Generated by create next app",
  },
  todos: {
    todo: "Todos",
    add: "Ajouter",
    addTodo: {
      title: "Ajouter une Todo",
      description: "Ajouter une nouvelle todo à votre liste",
      inputLabel: "Intitulé de la todo",
    },
  },
};
