apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: melone30/todo-app
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_JSON_SERVER_HOST
              value: "http://json-server-service"
            - name: NEXT_PUBLIC_JSON_SERVER_PORT
              value: "3001"
            - name: NEXT_PUBLIC_APP_PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: todo-app
