name: DEPLOY TODO APP

on:
  workflow_run:
    workflows: ["BUILD TODO APP"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $

      - name: Delete old Docker image
        run: docker rmi -f $DOCKER_USERNAME/todo-app:latest

      - name: Run the Docker container
        run: docker run -d -p 3000:3000 --name todo_container $DOCKER_USERNAME/todo-app:latest
