name: BUILD AND DEPLOY TODO APP

on:
  schedule:
    - cron: "09 10 * * *"
  push:
    branches: ["main"]
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Unit test
        run: pnpm test

      - name: Build with Next.js
        run: pnpm run build

      - name: Login to docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and push Docker image todo-app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-app:latest

      - name: Buils and push Docker image todo-app-json-server
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo_json_server:latest -f server/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/todo_json_server:latest

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Free disk space
        run: |
          sudo apt-get clean
          sudo apt-get autoclean
          sudo rm -rf /var/lib/apt/lists/*
          docker system prune -af
          docker volume prune -f

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Pull todo-app image
        run: docker pull $DOCKER_USERNAME/todo-app:latest

      - name: Pull todo-app-json-server image

        run: docker pull $DOCKER_USERNAME/todo_json_server:latest

      - name: List Docker images
        run: docker images

      - name: Delete old todo-app image
        run: docker rmi -f $DOCKER_USERNAME/todo-app:latest

      - name: Delete old todo_json_server image

        run: docker rmi -f $DOCKER_USERNAME/todo_json_server:latest

      - name: Run the todo-app container
        run: docker run -d -p 3000:3000 --name todocontainer $DOCKER_USERNAME/todo-app:latest

      - name: Run the todo_json_server container
        run: docker run -d -p 3001:3001 --name todo_json_server $DOCKER_USERNAME/todo_json_server:latest
