name: TODO APP

on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configurer Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose down --volumes --remove-orphans
          docker-compose up -d db

      # Étape 3 : Attendre que MySQL soit prêt
      - name: Wait for MySQL
        run: |
          until docker exec $(docker ps --filter "name=db" -q) mysqladmin ping -h"127.0.0.1" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      # Étape 4 : Construire et lancer l'application
      - name: Build and start application
        run: docker-compose up -d app

      # Étape 5 : Vérifier l'état des conteneurs
      - name: Check container statuses
        run: docker ps

      # Étape 6 : Tester l'application
      - name: Run application tests
        run: |
          docker exec $(docker ps --filter "name=app" -q) pnpm test

      # Étape 7 : Nettoyer les conteneurs Docker (optionnel)
      - name: Cleanup Docker
        if: always()
        run: docker-compose down --volumes --remove-orphans
